[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/bouk/monkey"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "~1.6.0"
