[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.0"
