[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/bouk/monkey"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "~1.6.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.0"

[[constraint]]
  name = "github.com/blang/semver"
  version = "~3.5.0"
